/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\syy-notes\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-17823082",
    path: "/css/canvas.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17823082").then(next)
    },
  },
  {
    name: "v-44a490a9",
    path: "/css/others.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44a490a9").then(next)
    },
  },
  {
    name: "v-eba34d5a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eba34d5a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-ca21f902",
    path: "/demo/cdn.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ca21f902").then(next)
    },
  },
  {
    name: "v-cccb8cd6",
    path: "/demo/docker.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cccb8cd6").then(next)
    },
  },
  {
    name: "v-e6854254",
    path: "/demo/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6854254").then(next)
    },
  },
  {
    path: "/demo/index.html",
    redirect: "/demo/"
  },
  {
    name: "v-2a894b56",
    path: "/demo/nextcloud.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a894b56").then(next)
    },
  },
  {
    name: "v-18000b95",
    path: "/demo/gogs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18000b95").then(next)
    },
  },
  {
    name: "v-30f72bca",
    path: "/css/layout.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30f72bca").then(next)
    },
  },
  {
    name: "v-1c283f65",
    path: "/demo/nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c283f65").then(next)
    },
  },
  {
    name: "v-2677ecfb",
    path: "/css/xuanran.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2677ecfb").then(next)
    },
  },
  {
    name: "v-065f06f5",
    path: "/demo/nginx-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-065f06f5").then(next)
    },
  },
  {
    name: "v-1e594cbb",
    path: "/demo/request.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e594cbb").then(next)
    },
  },
  {
    name: "v-0d25fc55",
    path: "/demo/suUI.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d25fc55").then(next)
    },
  },
  {
    name: "v-0ca60c79",
    path: "/frame/diff.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ca60c79").then(next)
    },
  },
  {
    name: "v-5fa7aeb5",
    path: "/demo/yanye.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fa7aeb5").then(next)
    },
  },
  {
    name: "v-64c2dd16",
    path: "/demo/vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64c2dd16").then(next)
    },
  },
  {
    name: "v-4dbad775",
    path: "/demo/vsftpd.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dbad775").then(next)
    },
  },
  {
    name: "v-01f8a496",
    path: "/demo/uni-template.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01f8a496").then(next)
    },
  },
  {
    name: "v-45c78e8a",
    path: "/frame/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45c78e8a").then(next)
    },
  },
  {
    name: "v-5247378a",
    path: "/frame/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5247378a").then(next)
    },
  },
  {
    name: "v-6cab505b",
    path: "/frame/props.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6cab505b").then(next)
    },
  },
  {
    name: "v-7cc15cd6",
    path: "/freeTalk/more.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cc15cd6").then(next)
    },
  },
  {
    name: "v-66aac276",
    path: "/freeTalk/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66aac276").then(next)
    },
  },
  {
    path: "/freeTalk/index.html",
    redirect: "/freeTalk/"
  },
  {
    name: "v-af22c540",
    path: "/introduce/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af22c540").then(next)
    },
  },
  {
    path: "/introduce/index.html",
    redirect: "/introduce/"
  },
  {
    name: "v-3043ab49",
    path: "/freeTalk/dairy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3043ab49").then(next)
    },
  },
  {
    name: "v-0cf4438c",
    path: "/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cf4438c").then(next)
    },
  },
  {
    path: "/git/index.html",
    redirect: "/git/"
  },
  {
    name: "v-3f699c6f",
    path: "/frame/mock.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f699c6f").then(next)
    },
  },
  {
    name: "v-003370aa",
    path: "/freeTalk/quest.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-003370aa").then(next)
    },
  },
  {
    name: "v-67822875",
    path: "/js/zancun.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67822875").then(next)
    },
  },
  {
    name: "v-c5734552",
    path: "/js/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c5734552").then(next)
    },
  },
  {
    name: "v-1b3b5d26",
    path: "/mix/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b3b5d26").then(next)
    },
  },
  {
    path: "/mix/index.html",
    redirect: "/mix/"
  },
  {
    name: "v-0be0489e",
    path: "/js/basic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0be0489e").then(next)
    },
  },
  {
    name: "v-359ba31b",
    path: "/mix/miniProgram.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-359ba31b").then(next)
    },
  },
  {
    name: "v-e9126b4a",
    path: "/mix/yukexcx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e9126b4a").then(next)
    },
  },
  {
    name: "v-698c2e02",
    path: "/mix/uniapp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-698c2e02").then(next)
    },
  },
  {
    name: "v-25ab460a",
    path: "/mix/flutter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25ab460a").then(next)
    },
  },
  {
    name: "v-51450200",
    path: "/mytools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51450200").then(next)
    },
  },
  {
    path: "/mytools/index.html",
    redirect: "/mytools/"
  },
  {
    name: "v-0abb5788",
    path: "/utils/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0abb5788").then(next)
    },
  },
  {
    path: "/utils/index.html",
    redirect: "/utils/"
  },
  {
    name: "v-4bd5f121",
    path: "/js/axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bd5f121").then(next)
    },
  },
  {
    name: "v-1922818e",
    path: "/utils/regexp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1922818e").then(next)
    },
  },
  {
    name: "v-410ccbca",
    path: "/mytools/fiddler.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-410ccbca").then(next)
    },
  },
  {
    name: "v-085d23f5",
    path: "/webGL/pixijs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-085d23f5").then(next)
    },
  },
  {
    name: "v-c888bb4a",
    path: "/mytools/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c888bb4a").then(next)
    },
  },
  {
    name: "v-56f7909b",
    path: "/utils/timestamp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56f7909b").then(next)
    },
  },
  {
    name: "v-0e8b2bfb",
    path: "/webGL/threejs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e8b2bfb").then(next)
    },
  },
  {
    name: "v-4c03892c",
    path: "/webGL/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c03892c").then(next)
    },
  },
  {
    path: "/webGL/index.html",
    redirect: "/webGL/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]