/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端小札",
  "description": "前端常用知识、踩坑记录荐等",
  "base": "/syy-notes/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/syy-notes/favicon.ico"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/syy-notes/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/syy-notes/favicon.ico"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/syy-notes/favicon.ico",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ]
  ],
  "pages": [
    {
      "title": "canvas",
      "frontmatter": {
        "sidebarDepth": 1
      },
      "regularPath": "/css/canvas.html",
      "relativePath": "css/canvas.md",
      "key": "v-17823082",
      "path": "/css/canvas.html",
      "headers": [
        {
          "level": 2,
          "title": "常用API",
          "slug": "常用api"
        },
        {
          "level": 2,
          "title": "微信小程序canvas 2d模式",
          "slug": "微信小程序canvas-2d模式"
        },
        {
          "level": 2,
          "title": "Canvas 3D",
          "slug": "canvas-3d"
        }
      ],
      "lastUpdated": "2021/5/4 下午2:47:10"
    },
    {
      "title": "滚动条样式",
      "frontmatter": {
        "sidebarDepth": 1
      },
      "regularPath": "/css/others.html",
      "relativePath": "css/others.md",
      "key": "v-44a490a9",
      "path": "/css/others.html",
      "lastUpdated": "2021/4/22 下午6:09:28"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "前端小札",
        "tagline": "唯有热爱，可抵岁月桓久",
        "heroImage": "/logo1.jpg",
        "actionText": "立即查看 →",
        "actionLink": "/introduce/",
        "features": [
          {
            "title": "JavaScript / Css 相关",
            "details": "夯实高级开发所需基础，提升编程技能及代码设计能力，学会阅读分析源码，建立健全完整的技术知识体系"
          },
          {
            "title": "Vue / React 相关",
            "details": "全方位分析前端主流框架React、Vue在项目中的应用、剖析核心源码以及内核机制、核心技术点、架构设计思想等，从根源解决开发难题"
          },
          {
            "title": "uni-app 相关",
            "details": "了解移动端适配常见难点，学习掌握小程序、公众号、app端等多种混合开发技术，记录实际业务需求及实现办法"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present | 简素言也"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-eba34d5a",
      "path": "/",
      "lastUpdated": "2021/5/25 下午6:14:37"
    },
    {
      "title": "CDN配置",
      "frontmatter": {},
      "regularPath": "/demo/cdn.html",
      "relativePath": "demo/cdn.md",
      "key": "v-ca21f902",
      "path": "/demo/cdn.html",
      "headers": [
        {
          "level": 2,
          "title": "静态资源cdn",
          "slug": "静态资源cdn"
        },
        {
          "level": 2,
          "title": "图床的使用",
          "slug": "图床的使用"
        },
        {
          "level": 3,
          "title": "比如GitHub",
          "slug": "比如github"
        },
        {
          "level": 2,
          "title": "公共库cdn",
          "slug": "公共库cdn"
        }
      ],
      "lastUpdated": "2021/6/5 下午11:31:27"
    },
    {
      "title": "Docker",
      "frontmatter": {},
      "regularPath": "/demo/docker.html",
      "relativePath": "demo/docker.md",
      "key": "v-cccb8cd6",
      "path": "/demo/docker.html",
      "headers": [
        {
          "level": 2,
          "title": "Docker",
          "slug": "docker"
        },
        {
          "level": 2,
          "title": "docker基本命令",
          "slug": "docker基本命令"
        },
        {
          "level": 3,
          "title": "新建一个Docker镜像",
          "slug": "新建一个docker镜像"
        },
        {
          "level": 3,
          "title": "将容器的状态保存为镜像",
          "slug": "将容器的状态保存为镜像"
        },
        {
          "level": 3,
          "title": "存储镜像",
          "slug": "存储镜像"
        },
        {
          "level": 2,
          "title": "什么是Docker",
          "slug": "什么是docker"
        },
        {
          "level": 3,
          "title": "从应用架构角度理解Docker",
          "slug": "从应用架构角度理解docker"
        },
        {
          "level": 3,
          "title": "从应用部署角度理解Docker",
          "slug": "从应用部署角度理解docker"
        },
        {
          "level": 3,
          "title": "从集群管理角度理解Docker",
          "slug": "从集群管理角度理解docker"
        }
      ],
      "lastUpdated": "2021/5/25 下午6:14:37"
    },
    {
      "title": "My Project",
      "frontmatter": {},
      "regularPath": "/demo/",
      "relativePath": "demo/README.md",
      "key": "v-e6854254",
      "path": "/demo/",
      "headers": [
        {
          "level": 3,
          "title": "1. 前端小札",
          "slug": "_1-前端小札"
        },
        {
          "level": 3,
          "title": "2. 言叶之庭",
          "slug": "_2-言叶之庭"
        },
        {
          "level": 3,
          "title": "3. syy-template",
          "slug": "_3-syy-template"
        },
        {
          "level": 3,
          "title": "4. suUI",
          "slug": "_4-suui"
        }
      ],
      "lastUpdated": "2021/6/5 下午11:31:27"
    },
    {
      "title": "nextcloud性能优化",
      "frontmatter": {},
      "regularPath": "/demo/nextcloud.html",
      "relativePath": "demo/nextcloud.md",
      "key": "v-2a894b56",
      "path": "/demo/nextcloud.html",
      "headers": [
        {
          "level": 3,
          "title": "1.更改后台执行方式",
          "slug": "_1-更改后台执行方式"
        },
        {
          "level": 3,
          "title": "2.内存缓存",
          "slug": "_2-内存缓存"
        },
        {
          "level": 3,
          "title": "3.启用http2，提高加载速度",
          "slug": "_3-启用http2-提高加载速度"
        },
        {
          "level": 3,
          "title": "4.停用无用的apps，降低系统负载",
          "slug": "_4-停用无用的apps-降低系统负载"
        },
        {
          "level": 3,
          "title": "5.上传速度优化",
          "slug": "_5-上传速度优化"
        }
      ],
      "lastUpdated": "2021/5/30 下午10:59:46"
    },
    {
      "title": "Gogs安装及使用",
      "frontmatter": {},
      "regularPath": "/demo/gogs.html",
      "relativePath": "demo/gogs.md",
      "key": "v-18000b95",
      "path": "/demo/gogs.html",
      "lastUpdated": "2021/5/25 下午6:14:37"
    },
    {
      "title": "CSS布局",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/css/layout.html",
      "relativePath": "css/layout.md",
      "key": "v-30f72bca",
      "path": "/css/layout.html",
      "headers": [
        {
          "level": 2,
          "title": "flex布局",
          "slug": "flex布局"
        },
        {
          "level": 2,
          "title": "Grid布局",
          "slug": "grid布局"
        }
      ],
      "lastUpdated": "2021/5/4 下午2:47:10"
    },
    {
      "title": "Linux安装Nginx正确方式",
      "frontmatter": {},
      "regularPath": "/demo/nginx.html",
      "relativePath": "demo/nginx.md",
      "key": "v-1c283f65",
      "path": "/demo/nginx.html",
      "headers": [
        {
          "level": 3,
          "title": "使用系统二进制源方式安装",
          "slug": "使用系统二进制源方式安装"
        },
        {
          "level": 3,
          "title": "编译安装",
          "slug": "编译安装"
        }
      ],
      "lastUpdated": "2021/5/28 下午6:07:15"
    },
    {
      "title": "【转】小程序同层渲染原理剖析",
      "frontmatter": {},
      "regularPath": "/css/xuanran.html",
      "relativePath": "css/xuanran.md",
      "key": "v-2677ecfb",
      "path": "/css/xuanran.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是「同层渲染」?",
          "slug": "什么是「同层渲染」"
        },
        {
          "level": 2,
          "title": "「同层渲染」原理",
          "slug": "「同层渲染」原理"
        },
        {
          "level": 3,
          "title": "iOS 端",
          "slug": "ios-端"
        },
        {
          "level": 3,
          "title": "Android 端",
          "slug": "android-端"
        },
        {
          "level": 2,
          "title": "「同层渲染」 Tips",
          "slug": "「同层渲染」-tips"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "2021/5/4 下午2:47:10"
    },
    {
      "title": "Nginx 常用配置汇总！从入门到干活足矣",
      "frontmatter": {},
      "regularPath": "/demo/nginx-config.html",
      "relativePath": "demo/nginx-config.md",
      "key": "v-065f06f5",
      "path": "/demo/nginx-config.html",
      "headers": [
        {
          "level": 2,
          "title": "Nginx简介",
          "slug": "nginx简介"
        },
        {
          "level": 2,
          "title": "基础配置",
          "slug": "基础配置"
        },
        {
          "level": 2,
          "title": "高级配置",
          "slug": "高级配置"
        },
        {
          "level": 2,
          "title": "安全配置",
          "slug": "安全配置"
        }
      ],
      "lastUpdated": "2021/5/28 下午6:07:15"
    },
    {
      "title": "关于request封装",
      "frontmatter": {},
      "regularPath": "/demo/request.html",
      "relativePath": "demo/request.md",
      "key": "v-1e594cbb",
      "path": "/demo/request.html",
      "lastUpdated": "2021/6/9 下午6:20:09"
    },
    {
      "title": "suUI",
      "frontmatter": {},
      "regularPath": "/demo/suUI.html",
      "relativePath": "demo/suUI.md",
      "key": "v-0d25fc55",
      "path": "/demo/suUI.html",
      "headers": [
        {
          "level": 2,
          "title": "搭建",
          "slug": "搭建"
        },
        {
          "level": 3,
          "title": "1. 项目初始化",
          "slug": "_1-项目初始化"
        },
        {
          "level": 3,
          "title": "2. 项目结构",
          "slug": "_2-项目结构"
        }
      ],
      "lastUpdated": "2021/4/26 下午5:32:55"
    },
    {
      "title": "Vue3",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/frame/diff.html",
      "relativePath": "frame/diff.md",
      "key": "v-0ca60c79",
      "path": "/frame/diff.html",
      "headers": [
        {
          "level": 2,
          "title": "一、composition API",
          "slug": "一、composition-api"
        },
        {
          "level": 3,
          "title": "回顾Mixins功能",
          "slug": "回顾mixins功能"
        },
        {
          "level": 3,
          "title": "快速入门Composition API",
          "slug": "快速入门composition-api"
        },
        {
          "level": 3,
          "title": "代码提取",
          "slug": "代码提取"
        },
        {
          "level": 3,
          "title": "代码重用",
          "slug": "代码重用"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "二、setup 的使用",
          "slug": "二、setup-的使用"
        },
        {
          "level": 2,
          "title": "三、深入 vue3 响应式原理",
          "slug": "三、深入-vue3-响应式原理"
        }
      ],
      "lastUpdated": "2021/6/5 下午11:31:27"
    },
    {
      "title": "言叶之庭",
      "frontmatter": {},
      "regularPath": "/demo/yanye.html",
      "relativePath": "demo/yanye.md",
      "key": "v-5fa7aeb5",
      "path": "/demo/yanye.html",
      "headers": [
        {
          "level": 2,
          "title": "服务器",
          "slug": "服务器"
        },
        {
          "level": 3,
          "title": "一、使用docker构建 Vue 应用镜像",
          "slug": "一、使用docker构建-vue-应用镜像"
        },
        {
          "level": 3,
          "title": "二、使用docker构建Node容器",
          "slug": "二、使用docker构建node容器"
        },
        {
          "level": 3,
          "title": "跨域转发",
          "slug": "跨域转发"
        },
        {
          "level": 3,
          "title": "改进",
          "slug": "改进"
        },
        {
          "level": 3,
          "title": "三、宿主机配置nginx搭建多端口站点",
          "slug": "三、宿主机配置nginx搭建多端口站点"
        },
        {
          "level": 3,
          "title": "四、配置CDN",
          "slug": "四、配置cdn"
        },
        {
          "level": 2,
          "title": "虚拟机教程",
          "slug": "虚拟机教程"
        },
        {
          "level": 3,
          "title": "1.新建centOS7 虚拟机",
          "slug": "_1-新建centos7-虚拟机"
        },
        {
          "level": 3,
          "title": "2.远程连接及建立ftp",
          "slug": "_2-远程连接及建立ftp"
        },
        {
          "level": 3,
          "title": "3.配置Docker环境",
          "slug": "_3-配置docker环境"
        },
        {
          "level": 3,
          "title": "4.自助git服务，私人仓库",
          "slug": "_4-自助git服务-私人仓库"
        },
        {
          "level": 3,
          "title": "5.搭建私有网盘",
          "slug": "_5-搭建私有网盘"
        },
        {
          "level": 2,
          "title": "更多",
          "slug": "更多"
        }
      ],
      "lastUpdated": "2021/6/3 下午6:12:15"
    },
    {
      "title": "前端小札",
      "frontmatter": {},
      "regularPath": "/demo/vuepress.html",
      "relativePath": "demo/vuepress.md",
      "key": "v-64c2dd16",
      "path": "/demo/vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 3,
          "title": "VuePress特性：",
          "slug": "vuepress特性"
        },
        {
          "level": 2,
          "title": "搭建",
          "slug": "搭建"
        },
        {
          "level": 3,
          "title": "全局安装VuePress",
          "slug": "全局安装vuepress"
        },
        {
          "level": 3,
          "title": "在project的根目录下新建docs文件夹：",
          "slug": "在project的根目录下新建docs文件夹"
        },
        {
          "level": 3,
          "title": "在docs文件夹下创建.vuepress文件夹：",
          "slug": "在docs文件夹下创建-vuepress文件夹"
        },
        {
          "level": 3,
          "title": "在.vuepress文件夹下面创建config.js:",
          "slug": "在-vuepress文件夹下面创建config-js"
        },
        {
          "level": 3,
          "title": "在.vuepress文件夹下面创建public文件夹:",
          "slug": "在-vuepress文件夹下面创建public文件夹"
        },
        {
          "level": 3,
          "title": "首页(像VuePress文档主页一样)",
          "slug": "首页-像vuepress文档主页一样"
        },
        {
          "level": 3,
          "title": "我们的项目结构已经搭好了：",
          "slug": "我们的项目结构已经搭好了"
        },
        {
          "level": 3,
          "title": "在 package.json 里添加两个启动命令:",
          "slug": "在-package-json-里添加两个启动命令"
        },
        {
          "level": 3,
          "title": "启动你的VuePress：",
          "slug": "启动你的vuepress"
        },
        {
          "level": 3,
          "title": "构建",
          "slug": "构建"
        },
        {
          "level": 2,
          "title": "基本配置",
          "slug": "基本配置"
        },
        {
          "level": 3,
          "title": "导航栏配置：",
          "slug": "导航栏配置"
        },
        {
          "level": 3,
          "title": "侧边栏配置：",
          "slug": "侧边栏配置"
        },
        {
          "level": 2,
          "title": "发布到github上",
          "slug": "发布到github上"
        },
        {
          "level": 3,
          "title": "在 docs/.vuepress/config.js 中设置正确的 base:",
          "slug": "在-docs-vuepress-config-js-中设置正确的-base"
        },
        {
          "level": 3,
          "title": "创建脚步文件",
          "slug": "创建脚步文件"
        },
        {
          "level": 3,
          "title": "设置package.json",
          "slug": "设置package-json"
        },
        {
          "level": 3,
          "title": "部署：",
          "slug": "部署"
        },
        {
          "level": 2,
          "title": "重点补充",
          "slug": "重点补充"
        },
        {
          "level": 2,
          "title": "前端小札2.0(重构中)",
          "slug": "前端小札2-0-重构中"
        },
        {
          "level": 3,
          "title": "VitePress新特性：",
          "slug": "vitepress新特性"
        },
        {
          "level": 3,
          "title": "其他的区别",
          "slug": "其他的区别"
        },
        {
          "level": 3,
          "title": "搭建",
          "slug": "搭建-2"
        }
      ],
      "lastUpdated": "2021/5/4 下午2:47:10"
    },
    {
      "title": "vsftp配置详解(转)",
      "frontmatter": {},
      "regularPath": "/demo/vsftpd.html",
      "relativePath": "demo/vsftpd.md",
      "key": "v-4dbad775",
      "path": "/demo/vsftpd.html",
      "lastUpdated": "2021/5/11 下午5:04:12"
    },
    {
      "title": "syy-template",
      "frontmatter": {},
      "regularPath": "/demo/uni-template.html",
      "relativePath": "demo/uni-template.md",
      "key": "v-01f8a496",
      "path": "/demo/uni-template.html",
      "headers": [
        {
          "level": 2,
          "title": "1.uniapp-template",
          "slug": "_1-uniapp-template"
        },
        {
          "level": 3,
          "title": "#构建过程",
          "slug": "构建过程"
        },
        {
          "level": 3,
          "title": "#可能问题：",
          "slug": "可能问题"
        }
      ],
      "lastUpdated": "2021/6/5 下午11:31:27"
    },
    {
      "title": "打包及性能优化",
      "frontmatter": {},
      "regularPath": "/frame/webpack.html",
      "relativePath": "frame/webpack.md",
      "key": "v-45c78e8a",
      "path": "/frame/webpack.html",
      "headers": [
        {
          "level": 3,
          "title": "1.vue-cli性能分析",
          "slug": "_1-vue-cli性能分析"
        },
        {
          "level": 3,
          "title": "2.webpack排除打包",
          "slug": "_2-webpack排除打包"
        },
        {
          "level": 3,
          "title": "3.CDN文件配置及注入",
          "slug": "_3-cdn文件配置及注入"
        }
      ],
      "lastUpdated": "2021/6/5 下午11:31:27"
    },
    {
      "title": "React",
      "frontmatter": {},
      "regularPath": "/frame/react.html",
      "relativePath": "frame/react.md",
      "key": "v-5247378a",
      "path": "/frame/react.html",
      "headers": [
        {
          "level": 3,
          "title": "组件间通信",
          "slug": "组件间通信"
        }
      ],
      "lastUpdated": "2021/6/5 下午11:31:27"
    },
    {
      "title": "深入Vue2",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/frame/props.html",
      "relativePath": "frame/props.md",
      "key": "v-6cab505b",
      "path": "/frame/props.html",
      "headers": [
        {
          "level": 3,
          "title": "一、响应式原理",
          "slug": "一、响应式原理"
        },
        {
          "level": 2,
          "title": "ES5和ES6中set和get方法",
          "slug": "es5和es6中set和get方法"
        },
        {
          "level": 3,
          "title": "二、组件之间传值",
          "slug": "二、组件之间传值"
        },
        {
          "level": 3,
          "title": "二、缓存",
          "slug": "二、缓存"
        },
        {
          "level": 3,
          "title": "三、VueX",
          "slug": "三、vuex"
        }
      ],
      "lastUpdated": "2021/6/5 下午11:31:27"
    },
    {
      "title": "未完待续...",
      "frontmatter": {},
      "regularPath": "/freeTalk/more.html",
      "relativePath": "freeTalk/more.md",
      "key": "v-7cc15cd6",
      "path": "/freeTalk/more.html",
      "lastUpdated": "2021/4/26 下午5:32:55"
    },
    {
      "title": "随便写写",
      "frontmatter": {},
      "regularPath": "/freeTalk/",
      "relativePath": "freeTalk/README.md",
      "key": "v-66aac276",
      "path": "/freeTalk/",
      "lastUpdated": "2021/4/26 下午5:32:55"
    },
    {
      "frontmatter": {},
      "regularPath": "/introduce/",
      "relativePath": "introduce/README.md",
      "key": "v-af22c540",
      "path": "/introduce/",
      "lastUpdated": "2021/5/25 下午6:14:37"
    },
    {
      "title": "日记杂记",
      "frontmatter": {},
      "regularPath": "/freeTalk/dairy.html",
      "relativePath": "freeTalk/dairy.md",
      "key": "v-3043ab49",
      "path": "/freeTalk/dairy.html",
      "headers": [
        {
          "level": 3,
          "title": "日记杂记",
          "slug": "日记杂记"
        }
      ],
      "lastUpdated": "2021/5/28 下午6:07:15"
    },
    {
      "title": "Git",
      "frontmatter": {
        "sidebarDepth": 3
      },
      "regularPath": "/git/",
      "relativePath": "git/README.md",
      "key": "v-0cf4438c",
      "path": "/git/",
      "headers": [
        {
          "level": 2,
          "title": "备忘API",
          "slug": "备忘api"
        },
        {
          "level": 3,
          "title": "初始化",
          "slug": "初始化"
        },
        {
          "level": 3,
          "title": "关联远端仓库",
          "slug": "关联远端仓库"
        },
        {
          "level": 3,
          "title": "分支",
          "slug": "分支"
        },
        {
          "level": 3,
          "title": "tag相关",
          "slug": "tag相关"
        },
        {
          "level": 3,
          "title": "重置",
          "slug": "重置"
        },
        {
          "level": 3,
          "title": "小技巧",
          "slug": "小技巧"
        },
        {
          "level": 2,
          "title": "拓展",
          "slug": "拓展"
        },
        {
          "level": 3,
          "title": "1. git托管多平台",
          "slug": "_1-git托管多平台"
        },
        {
          "level": 3,
          "title": "2. Git Hooks",
          "slug": "_2-git-hooks"
        },
        {
          "level": 3,
          "title": "3. Github Actions",
          "slug": "_3-github-actions"
        },
        {
          "level": 3,
          "title": "4.  gh-pages插件",
          "slug": "_4-gh-pages插件"
        }
      ],
      "lastUpdated": "2021/5/17 下午10:15:31"
    },
    {
      "title": "Mock.js",
      "frontmatter": {},
      "regularPath": "/frame/mock.html",
      "relativePath": "frame/mock.md",
      "key": "v-3f699c6f",
      "path": "/frame/mock.html",
      "headers": [
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        }
      ],
      "lastUpdated": "2021/6/5 下午11:31:27"
    },
    {
      "title": "Just For interView",
      "frontmatter": {
        "sidebarDepth": 5
      },
      "regularPath": "/freeTalk/quest.html",
      "relativePath": "freeTalk/quest.md",
      "key": "v-003370aa",
      "path": "/freeTalk/quest.html",
      "headers": [
        {
          "level": 2,
          "title": "Just For interView",
          "slug": "just-for-interview"
        },
        {
          "level": 3,
          "title": "1. 什么是闭包",
          "slug": "_1-什么是闭包"
        },
        {
          "level": 3,
          "title": "2. 什么是原型链",
          "slug": "_2-什么是原型链"
        },
        {
          "level": 3,
          "title": "3. ES6新语法",
          "slug": "_3-es6新语法"
        },
        {
          "level": 3,
          "title": "4. 数组有哪些方法",
          "slug": "_4-数组有哪些方法"
        },
        {
          "level": 3,
          "title": "5. Get和post的区别",
          "slug": "_5-get和post的区别"
        },
        {
          "level": 3,
          "title": "6. ES6的继承和ES5的继承有什么不同",
          "slug": "_6-es6的继承和es5的继承有什么不同"
        },
        {
          "level": 3,
          "title": "7. 深拷贝，浅拷贝",
          "slug": "_7-深拷贝-浅拷贝"
        },
        {
          "level": 3,
          "title": "8. Event Loop（事件循环机制)",
          "slug": "_8-event-loop-事件循环机制"
        },
        {
          "level": 3,
          "title": "9. 什么是BFC",
          "slug": "_9-什么是bfc"
        },
        {
          "level": 3,
          "title": "10. 浏览器渲染html页面的一般过程",
          "slug": "_10-浏览器渲染html页面的一般过程"
        },
        {
          "level": 3,
          "title": "11. 清除浮动的多种方式",
          "slug": "_11-清除浮动的多种方式"
        },
        {
          "level": 3,
          "title": "12. 继承的几种方式及优缺点",
          "slug": "_12-继承的几种方式及优缺点"
        },
        {
          "level": 3,
          "title": "13. GC垃圾回收机制",
          "slug": "_13-gc垃圾回收机制"
        },
        {
          "level": 3,
          "title": "14. 回流重绘",
          "slug": "_14-回流重绘"
        },
        {
          "level": 3,
          "title": "15. 跨域",
          "slug": "_15-跨域"
        },
        {
          "level": 3,
          "title": "16. 什么是mvvm什么是mvc",
          "slug": "_16-什么是mvvm什么是mvc"
        }
      ],
      "lastUpdated": "2021/4/26 下午5:32:55"
    },
    {
      "title": "什么是shim 和 polyfill，@param",
      "frontmatter": {},
      "regularPath": "/js/zancun.html",
      "relativePath": "js/zancun.md",
      "key": "v-67822875",
      "path": "/js/zancun.html",
      "headers": [
        {
          "level": 2,
          "title": "Shim",
          "slug": "shim"
        },
        {
          "level": 2,
          "title": "Polyfill",
          "slug": "polyfill"
        },
        {
          "level": 2,
          "title": "JavaScript的@param注解",
          "slug": "javascript的-param注解"
        },
        {
          "level": 2,
          "title": "什么是Calc",
          "slug": "什么是calc"
        },
        {
          "level": 2,
          "title": "// 隐藏scroll-view的滚动条",
          "slug": "隐藏scroll-view的滚动条"
        },
        {
          "level": 2,
          "title": "背景分析:",
          "slug": "背景分析"
        },
        {
          "level": 2,
          "title": "那怎么去实时地知道服务器的状态呢？",
          "slug": "那怎么去实时地知道服务器的状态呢"
        },
        {
          "level": 2,
          "title": "WebSocket 协议",
          "slug": "websocket-协议"
        },
        {
          "level": 2,
          "title": "http 长连接和 websocket 的长连接区别",
          "slug": "http-长连接和-websocket-的长连接区别"
        },
        {
          "level": 2,
          "title": "Socket.IO 的引入",
          "slug": "socket-io-的引入"
        },
        {
          "level": 2,
          "title": "解决方案",
          "slug": "解决方案"
        },
        {
          "level": 3,
          "title": "1. JSONP",
          "slug": "_1-jsonp"
        },
        {
          "level": 3,
          "title": "2. CORS",
          "slug": "_2-cors"
        },
        {
          "level": 3,
          "title": "3. Webpack反向代理（主流方法）",
          "slug": "_3-webpack反向代理-主流方法"
        },
        {
          "level": 3,
          "title": "4. Nginx反向代理 （主流方法）",
          "slug": "_4-nginx反向代理-主流方法"
        },
        {
          "level": 3,
          "title": "5. webSocket（高级小众方法）",
          "slug": "_5-websocket-高级小众方法"
        },
        {
          "level": 3,
          "title": "对于prototype的认识",
          "slug": "对于prototype的认识"
        },
        {
          "level": 3,
          "title": "对于_proto_的的认识",
          "slug": "对于-proto-的的认识"
        },
        {
          "level": 3,
          "title": "prototype和_proto_的关系",
          "slug": "prototype和-proto-的关系"
        },
        {
          "level": 3,
          "title": "序",
          "slug": "序"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        },
        {
          "level": 3,
          "title": "菜单栏控制",
          "slug": "菜单栏控制"
        },
        {
          "level": 3,
          "title": "界面的控制",
          "slug": "界面的控制"
        },
        {
          "level": 3,
          "title": "按钮的控制",
          "slug": "按钮的控制"
        },
        {
          "level": 3,
          "title": "请求的控制",
          "slug": "请求的控制"
        }
      ],
      "lastUpdated": "2021/5/26 下午6:05:07"
    },
    {
      "title": "Promise",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/js/promise.html",
      "relativePath": "js/promise.md",
      "key": "v-c5734552",
      "path": "/js/promise.html",
      "headers": [
        {
          "level": 3,
          "title": "理解",
          "slug": "理解"
        },
        {
          "level": 3,
          "title": "缺点",
          "slug": "缺点"
        },
        {
          "level": 3,
          "title": "构造",
          "slug": "构造"
        },
        {
          "level": 3,
          "title": "then的实现",
          "slug": "then的实现"
        }
      ],
      "lastUpdated": "2021/5/7 下午6:07:15"
    },
    {
      "title": "1. Uni-app",
      "frontmatter": {},
      "regularPath": "/mix/",
      "relativePath": "mix/README.md",
      "key": "v-1b3b5d26",
      "path": "/mix/",
      "headers": [
        {
          "level": 3,
          "title": "1. Uni-app",
          "slug": "_1-uni-app"
        },
        {
          "level": 3,
          "title": "2. Flutter",
          "slug": "_2-flutter"
        }
      ],
      "lastUpdated": "2021/5/25 下午6:14:37"
    },
    {
      "title": "JS基础",
      "frontmatter": {},
      "regularPath": "/js/basic.html",
      "relativePath": "js/basic.md",
      "key": "v-0be0489e",
      "path": "/js/basic.html",
      "lastUpdated": "2021/5/4 下午2:47:10"
    },
    {
      "title": "Uni-app微信小程序",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/mix/miniProgram.html",
      "relativePath": "mix/miniProgram.md",
      "key": "v-359ba31b",
      "path": "/mix/miniProgram.html",
      "headers": [
        {
          "level": 2,
          "title": "一、微信授权登录全流程",
          "slug": "一、微信授权登录全流程"
        },
        {
          "level": 2,
          "title": "二、微信支付全流程",
          "slug": "二、微信支付全流程"
        },
        {
          "level": 2,
          "title": "三、动态计算显示高度",
          "slug": "三、动态计算显示高度"
        },
        {
          "level": 2,
          "title": "四、scroll吸附贴顶效果",
          "slug": "四、scroll吸附贴顶效果"
        },
        {
          "level": 2,
          "title": "五、小程序生成海报图片并保存至本地",
          "slug": "五、小程序生成海报图片并保存至本地"
        }
      ],
      "lastUpdated": "2021/5/29 下午6:02:30"
    },
    {
      "frontmatter": {},
      "regularPath": "/mix/yukexcx.html",
      "relativePath": "mix/yukexcx.md",
      "key": "v-e9126b4a",
      "path": "/mix/yukexcx.html",
      "lastUpdated": "2021/5/25 下午6:14:37"
    },
    {
      "title": "Uni-app",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/mix/uniapp.html",
      "relativePath": "mix/uniapp.md",
      "key": "v-698c2e02",
      "path": "/mix/uniapp.html",
      "headers": [
        {
          "level": 2,
          "title": "一、vue文件",
          "slug": "一、vue文件"
        },
        {
          "level": 2,
          "title": "二、nvue文件",
          "slug": "二、nvue文件"
        },
        {
          "level": 2,
          "title": "三、构建uniapp项目",
          "slug": "三、构建uniapp项目"
        },
        {
          "level": 2,
          "title": "四、uniapp的一些坑",
          "slug": "四、uniapp的一些坑"
        }
      ],
      "lastUpdated": "2021/6/1 下午8:16:31"
    },
    {
      "title": "Flutter",
      "frontmatter": {},
      "regularPath": "/mix/flutter.html",
      "relativePath": "mix/flutter.md",
      "key": "v-25ab460a",
      "path": "/mix/flutter.html",
      "headers": [
        {
          "level": 2,
          "title": "开发环境搭建准备工作：",
          "slug": "开发环境搭建准备工作"
        },
        {
          "level": 2,
          "title": "1、flutter 安装",
          "slug": "_1、flutter-安装"
        },
        {
          "level": 2,
          "title": "2、安装Xcode",
          "slug": "_2、安装xcode"
        },
        {
          "level": 2,
          "title": "3、安装Android Studio",
          "slug": "_3、安装android-studio"
        },
        {
          "level": 2,
          "title": "4、安装 android-licenses",
          "slug": "_4、安装-android-licenses"
        },
        {
          "level": 2,
          "title": "5、安装 Xcode 包管理工具",
          "slug": "_5、安装-xcode-包管理工具"
        },
        {
          "level": 2,
          "title": "6、安装手机模拟器",
          "slug": "_6、安装手机模拟器"
        },
        {
          "level": 2,
          "title": "7、创建一个项目：",
          "slug": "_7、创建一个项目"
        }
      ],
      "lastUpdated": "2021/5/25 下午6:14:37"
    },
    {
      "title": "个人工具",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/mytools/",
      "relativePath": "mytools/README.md",
      "key": "v-51450200",
      "path": "/mytools/",
      "headers": [
        {
          "level": 3,
          "title": "个人工具",
          "slug": "个人工具"
        },
        {
          "level": 3,
          "title": "",
          "slug": ""
        }
      ],
      "lastUpdated": "2021/5/29 下午6:02:30"
    },
    {
      "title": "代码片段",
      "frontmatter": {},
      "regularPath": "/utils/",
      "relativePath": "utils/README.md",
      "key": "v-0abb5788",
      "path": "/utils/",
      "headers": [
        {
          "level": 3,
          "title": "1.常用正则",
          "slug": "_1-常用正则"
        },
        {
          "level": 3,
          "title": "2.常用时间戳转换",
          "slug": "_2-常用时间戳转换"
        }
      ],
      "lastUpdated": "2021/4/26 下午5:32:55"
    },
    {
      "title": "Axios",
      "frontmatter": {},
      "regularPath": "/js/axios.html",
      "relativePath": "js/axios.md",
      "key": "v-4bd5f121",
      "path": "/js/axios.html",
      "headers": [
        {
          "level": 3,
          "title": "1.根据环境变量区分接口地址",
          "slug": "_1-根据环境变量区分接口地址"
        },
        {
          "level": 3,
          "title": "2.设置请求超时",
          "slug": "_2-设置请求超时"
        },
        {
          "level": 3,
          "title": "3.设置请求头",
          "slug": "_3-设置请求头"
        },
        {
          "level": 3,
          "title": "4.设置请求拦截器",
          "slug": "_4-设置请求拦截器"
        },
        {
          "level": 3,
          "title": "5.设置响应拦截器",
          "slug": "_5-设置响应拦截器"
        }
      ],
      "lastUpdated": "2021/5/4 下午2:47:10"
    },
    {
      "title": "常用正则",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/utils/regexp.html",
      "relativePath": "utils/regexp.md",
      "key": "v-1922818e",
      "path": "/utils/regexp.html",
      "headers": [
        {
          "level": 2,
          "title": "验证相关",
          "slug": "验证相关"
        },
        {
          "level": 3,
          "title": "是否是金额（精确到分）",
          "slug": "是否是金额-精确到分"
        },
        {
          "level": 3,
          "title": "是否是手机号",
          "slug": "是否是手机号"
        },
        {
          "level": 3,
          "title": "是否是邮箱号",
          "slug": "是否是邮箱号"
        },
        {
          "level": 3,
          "title": "是否是 QQ 号",
          "slug": "是否是-qq-号"
        },
        {
          "level": 3,
          "title": "是否是链接地址",
          "slug": "是否是链接地址"
        },
        {
          "level": 3,
          "title": "是否是身份证号码",
          "slug": "是否是身份证号码"
        },
        {
          "level": 2,
          "title": "格式相关",
          "slug": "格式相关"
        },
        {
          "level": 3,
          "title": "344 格式手机号",
          "slug": "_344-格式手机号"
        },
        {
          "level": 3,
          "title": "隐藏手机号中间 4 位",
          "slug": "隐藏手机号中间-4-位"
        }
      ],
      "lastUpdated": "2021/4/12 下午4:22:10"
    },
    {
      "title": "Fiddler抓包工具总结",
      "frontmatter": {},
      "regularPath": "/mytools/fiddler.html",
      "relativePath": "mytools/fiddler.md",
      "key": "v-410ccbca",
      "path": "/mytools/fiddler.html",
      "headers": [
        {
          "level": 2,
          "title": "序章",
          "slug": "序章"
        },
        {
          "level": 2,
          "title": "1. Fiddler 抓包简介",
          "slug": "_1-fiddler-抓包简介"
        },
        {
          "level": 3,
          "title": "1） 字段说明",
          "slug": "_1-字段说明"
        },
        {
          "level": 3,
          "title": "2）. Statistics 请求的性能数据分析",
          "slug": "_2-statistics-请求的性能数据分析"
        },
        {
          "level": 3,
          "title": "3）. Inspectors 查看数据内容",
          "slug": "_3-inspectors-查看数据内容"
        },
        {
          "level": 3,
          "title": "4）. AutoResponder 允许拦截指定规则的请求",
          "slug": "_4-autoresponder-允许拦截指定规则的请求"
        },
        {
          "level": 3,
          "title": "4）. Composer 自定义请求发送服务器",
          "slug": "_4-composer-自定义请求发送服务器"
        },
        {
          "level": 3,
          "title": "5）. Filters 请求过滤规则",
          "slug": "_5-filters-请求过滤规则"
        },
        {
          "level": 2,
          "title": "2. Fiddler 设置解密HTTPS的网络数据",
          "slug": "_2-fiddler-设置解密https的网络数据"
        },
        {
          "level": 2,
          "title": "3. Fiddler 抓取Iphone / Android数据包",
          "slug": "_3-fiddler-抓取iphone-android数据包"
        },
        {
          "level": 2,
          "title": "4. Fiddler 内置命令与断点",
          "slug": "_4-fiddler-内置命令与断点"
        },
        {
          "level": 2,
          "title": "Stream",
          "slug": "stream"
        },
        {
          "level": 2,
          "title": "har文件",
          "slug": "har文件"
        }
      ],
      "lastUpdated": "2021/5/28 下午6:07:15"
    },
    {
      "title": "Pixi.js",
      "frontmatter": {},
      "regularPath": "/webGL/pixijs.html",
      "relativePath": "webGL/pixijs.md",
      "key": "v-085d23f5",
      "path": "/webGL/pixijs.html",
      "headers": [
        {
          "level": 2,
          "title": "搭建环境",
          "slug": "搭建环境"
        },
        {
          "level": 2,
          "title": "快速开始",
          "slug": "快速开始"
        },
        {
          "level": 2,
          "title": "基本概念",
          "slug": "基本概念"
        },
        {
          "level": 2,
          "title": "Container",
          "slug": "container"
        },
        {
          "level": 2,
          "title": "Renderer",
          "slug": "renderer"
        },
        {
          "level": 2,
          "title": "Sprite",
          "slug": "sprite"
        },
        {
          "level": 2,
          "title": "Loader",
          "slug": "loader"
        },
        {
          "level": 2,
          "title": "Ticker",
          "slug": "ticker"
        },
        {
          "level": 2,
          "title": "补间动画",
          "slug": "补间动画"
        },
        {
          "level": 2,
          "title": "自定义的Application",
          "slug": "自定义的application"
        },
        {
          "level": 2,
          "title": "参考",
          "slug": "参考"
        },
        {
          "level": 2,
          "title": "案例",
          "slug": "案例"
        }
      ],
      "lastUpdated": "2021/5/26 下午6:05:07"
    },
    {
      "title": "Linux常用指令",
      "frontmatter": {},
      "regularPath": "/mytools/linux.html",
      "relativePath": "mytools/linux.md",
      "key": "v-c888bb4a",
      "path": "/mytools/linux.html",
      "lastUpdated": "2021/5/12 下午6:17:00"
    },
    {
      "title": "时间戳",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/utils/timestamp.html",
      "relativePath": "utils/timestamp.md",
      "key": "v-56f7909b",
      "path": "/utils/timestamp.html",
      "headers": [
        {
          "level": 2,
          "title": "获取当前时间戳",
          "slug": "获取当前时间戳"
        },
        {
          "level": 2,
          "title": "时间戳转化为年月日小时分钟",
          "slug": "时间戳转化为年月日小时分钟"
        },
        {
          "level": 2,
          "title": "Moment.js",
          "slug": "moment-js"
        }
      ],
      "lastUpdated": "2021/4/30 下午11:09:56"
    },
    {
      "title": "Threejs",
      "frontmatter": {},
      "regularPath": "/webGL/threejs.html",
      "relativePath": "webGL/threejs.md",
      "key": "v-0e8b2bfb",
      "path": "/webGL/threejs.html",
      "lastUpdated": "2021/5/6 下午6:11:03"
    },
    {
      "title": "WebGL",
      "frontmatter": {},
      "regularPath": "/webGL/",
      "relativePath": "webGL/README.md",
      "key": "v-4c03892c",
      "path": "/webGL/",
      "headers": [
        {
          "level": 3,
          "title": "webGL是什么",
          "slug": "webgl是什么"
        },
        {
          "level": 3,
          "title": "1. Three.js 点击跳转",
          "slug": "_1-three-js-点击跳转"
        },
        {
          "level": 3,
          "title": "2. pixi.js 点击跳转",
          "slug": "_2-pixi-js-点击跳转"
        },
        {
          "level": 3,
          "title": "3. babylon.js",
          "slug": "_3-babylon-js"
        }
      ],
      "lastUpdated": "2021/5/12 下午6:17:00"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "工作项目",
        "items": [
          {
            "text": "后台管理系统",
            "link": "http://admin.yuke520.com/"
          },
          {
            "text": "裕客商城小程序",
            "link": "../uniapp/yukexcx"
          }
        ]
      },
      {
        "text": " suUI ",
        "link": "https://yu-nan.gitee.io/suui"
      },
      {
        "text": "言叶之庭",
        "link": "http://www.syy123.com"
      },
      {
        "text": "关于",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/suyanye123/syy-notes"
          },
          {
            "text": "关于我",
            "link": "../introduce/"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "网页工具",
        "path": "/mytools/"
      },
      {
        "title": "我的项目",
        "path": "/demo/",
        "children": [
          "demo/vuepress",
          "demo/yanye",
          "demo/uni-template",
          "demo/suUI"
        ]
      },
      {
        "title": "CSS",
        "children": [
          "css/layout",
          "css/others",
          "css/canvas"
        ]
      },
      {
        "title": "JavaScript",
        "children": [
          "js/basic",
          "js/promise",
          "js/axios"
        ]
      },
      {
        "title": "框架",
        "children": [
          "frame/props",
          "frame/webpack",
          "frame/diff",
          "frame/react",
          "frame/mock"
        ]
      },
      {
        "title": "混合开发",
        "path": "/mix/",
        "children": [
          "mix/uniapp",
          "mix/miniProgram",
          "mix/flutter"
        ]
      },
      {
        "title": "Git",
        "path": "/git/"
      },
      {
        "title": "WebGL",
        "path": "/webGL/",
        "children": [
          "webGL/threejs",
          "webGL/pixijs"
        ]
      },
      {
        "title": "utils",
        "path": "/utils/",
        "children": [
          "utils/timestamp",
          "utils/regexp"
        ]
      },
      {
        "title": "写点东西",
        "path": "/freeTalk/",
        "children": [
          "freeTalk/quest",
          "freeTalk/dairy",
          "freeTalk/more"
        ]
      }
    ],
    "lastUpdated": "上次更新"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "前端小札",
      "description": "前端常用知识、踩坑记录等",
      "path": "/"
    }
  }
}